### ISSUE TITLE
localhost:5443/settings An unhandled exception has occurred

### ISSUE THREAD

**Issue by LEIRONGHUA** [Aguafrommars/DynamicConfiguration#29]
**Describe the bug**
GET URL: https://localhost:5443/api/api/configuration/Aguacongas.TheIdServer.BlazorApp.Models.ServerConfig,%20Aguacongas.TheIdServer.BlazorApp.Infrastructure,%20Version=1.0.0.0,%20Culture=neutral,%20PublicKeyToken=null
![image](https://user-images.githubusercontent.com/4002277/215370141-59cbf0ad-a8f4-4306-9e29-5139d7860449.png)
![image](https://user-images.githubusercontent.com/4002277/215370179-2aafe9e3-61f9-4ac8-8702-24f6a12f0989.png)

**Logs**
System.InvalidOperationException: Failed to convert configuration value at 'TokenCleanupInterval' to type 'System.TimeSpan'.
 ---> System.FormatException: "00:05:00" is not a valid value for TimeSpan.
 ---> System.FormatException: String '"00:05:00"' was not recognized as a valid TimeSpan.
   at System.Globalization.TimeSpanParse.TimeSpanResult.SetBadTimeSpanFailure()
   at System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.ProcessTerminalState(TimeSpanRawInfo& raw, TimeSpanStandardStyles style, TimeSpanResult& result)
   at System.Globalization.TimeSpanParse.TryParseTimeSpan(ReadOnlySpan`1 input, TimeSpanStandardStyles style, IFormatProvider formatProvider, TimeSpanResult& result)
   at System.TimeSpan.Parse(String input, IFormatProvider formatProvider)
   at System.ComponentModel.TimeSpanConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   .........   
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.Authenticate(HttpContext context, Func`1 next, String basePath, String authicationScheme) in D:\Work\SourceCode\Git\TheIdServer\src\IdentityServer\Duende\Aguacongas.IdentityServer.Admin.Duende\Extensions\EndpointRoutingApplicationBuilderExtensions.cs:line 138

**Platform (please complete the following information):**
 - OS: Windows 11 22H2（22621.1194）
 - .Net Core Version 7.0.102

**Comment by aguacongas** [comment]
@LEIRONGHUA I moved the issue in DynamicConfiguration because it's related to the `Aguacongas.DynamicConfiguration.Redis` lib.  
To workaround you can delete Redis hash key by using **redis-cli** on your redis DB : `hdel Aguacongas.TheIdServer.Duende TokenCleanupInterval`

**Comment by aguacongas** [comment]
@LEIRONGHUA yes, it's because the value is stored into redis db, you need to delete it using redis-cli

**Comment by LEIRONGHUA** [comment]
@aguacongas 
Yes, Redis has been removed, and the problem with the 500 status has been resolved.
What I am reporting now is another BUG on the settings page.
Error in blazor.webassembly.js in browser
Please open the link to see: https://theidserver-duende.herokuapp.com/settings

**Comment by aguacongas** [comment]
Ok, can you open a new bug at https://github.com/Aguafrommars/TheIdServer/issues please

**Comment by LEIRONGHUA** [comment]
Ok, A new bug has been created: https://github.com/Aguafrommars/TheIdServer/issues/944#issue-1567399461
